### ISSUE TITLE
Generate Keys not working

### ISSUE THREAD

**Issue by airbeat92** [jkrauze/mceliece#4]
I am getting the following error, when I try to generate the keys:

Traceback (most recent call last):
  File "...Projekt/McEliece - python/mceliece/./mceliece.py", line 143, in <module>
    generate(int(args['M']), int(args['N']), int(args['T']), args['PRIV_KEY_FILE'], args['PUB_KEY_FILE'])
  File "...Projekt/McEliece - python/mceliece/./mceliece.py", line 41, in generate
    mceliece.generate_random_keys()
  File "...Projekt/McEliece - python/mceliece/mceliece/mceliececipher.py", line 29, in generate_random_keys
    self.G, self.H, self.g_poly, self.irr_poly = GoppaCodeGenerator(self.m, self.n, self.t).gen()
  File "...Projekt/McEliece - python/mceliece/goppa/goppacodegenerator.py", line 88, in gen
    H_nullspace, nullity = H_bin.nullspace()
  File "...Projekt/McEliece - python/mceliece/mceliece/mathutils.py", line 495, in nullspace
    X, nullity = self.to_flint().nullspace()
  File "...Projekt/McEliece - python/mceliece/mceliece/mathutils.py", line 492, in to_flint
    return flint.nmod_mat(self.arr.shape[0], self.arr.shape[1], [int(e) for e in self.arr.flatten()], 2)
AttributeError: module 'flint' has no attribute 'nmod_mat'

**Comment by Ganeshvani** [comment]
Traceback (most recent call last):
  File "./mceliece.py", line 143, in <module>
    generate(int(args['M']), int(args['N']), int(args['T']), args['PRIV_KEY_FILE'], args['PUB_KEY_FILE'])
  File "./mceliece.py", line 41, in generate
    mceliece.generate_random_keys()
  File "/home/projectcbc/Downloads/mceliece-master/mceliece/mceliececipher.py", line 29, in generate_random_keys
    self.G, self.H, self.g_poly, self.irr_poly = GoppaCodeGenerator(self.m, self.n, self.t).gen()
  File "/home/projectcbc/Downloads/mceliece-master/goppa/goppacodegenerator.py", line 88, in gen
    H_nullspace, nullity = H_bin.nullspace()
  File "/home/projectcbc/Downloads/mceliece-master/mceliece/mathutils.py", line 495, in nullspace
    X, nullity = self.to_flint().nullspace()
  File "/home/projectcbc/Downloads/mceliece-master/mceliece/mathutils.py", line 492, in to_flint
    return flint.nmod_mat(self.arr.shape[0], self.arr.shape[1], [int(e) for e in self.arr.flatten()], 2)
AttributeError: module 'flint' has no attribute 'nmod_mat'

Getting above error while generating keys.. please help

**Comment by jkrauze** [comment]
I've just added the `requirements.txt` file. You can make sure you have all required dependencies by running the following command:
```shell
pip install -r requirements.txt
```

The issue you're guys mentioning is caused by using the obsolete `flint` module instead of the `python-flint` one. You might need to uninstall it (`pip uninstall flint`) to make the code run properly.

**Comment by MihalacheStefan** [comment]
I'm still getting this exception no matter what input I give for key generation. Can someone post a set of parameters that works for them such that I'm sure that I don't miss anything regarding the way McEliece key generation works?

Traceback (most recent call last):
  File "./mceliece.py", line 140, in <module>
    generate(int(args['M']), int(args['N']), int(args['T']), args['PRIV_KEY_FILE'], args['PUB_KEY_FILE'])
  File "./mceliece.py", line 38, in generate
    mceliece.generate_random_keys()
  File ".../mceliece/mceliececipher.py", line 27, in generate_random_keys
    self.G, self.H, self.g_poly, self.irr_poly = GoppaCodeGenerator(self.m, self.n, self.t).gen()
  File ".../goppa/goppacodegenerator.py", line 63, in gen
    raise Exception("irr poly not found")
