### ISSUE TITLE
Values of m, n, t??

### ISSUE THREAD

**Issue by rkarn** [jkrauze/mceliece#8]
I need m>8, n>20 and t>3

I run the following command to generate keys:
python3 mceliece.py -v gen 8 20 3 PRIV_KEY_FILE PUB_KEY_FILE

I get below error:

Traceback (most recent call last):
  File "/root/mceliece/mceliece.py", line 147, in <module>
    generate(int(args['M']), int(args['N']), int(args['T']), args['PRIV_KEY_FILE'], args['PUB_KEY_FILE'])
  File "/root/mceliece/mceliece.py", line 44, in generate
    mceliece.generate_random_keys()
  File "/root/mceliece/mceliece/mceliececipher.py", line 37, in generate_random_keys
    self.S_inv = self.S.inv()
  File "/root/mceliece/mceliece/mathutils.py", line 503, in inv
    eye = flint.nmod_mat(self.arr.shape[0], self.arr.shape[1],
IndexError: tuple index out of range

How to set the correct combination of m,n,t?

**Comment by byAhro** [comment]
Hi, I see that you have got the same problem like me. I found out that there is a few options to generate the pair of the keys but only one is giving fine plainText after decryption.  Is there any solution to use the parametrs like from article which I am attaching belove?
https://eprint.iacr.org/2010/271.pdf

**Comment by rkarn** [comment]
Hi @byAhro , in the paper you attached, the value of parameters are huge. My machine is unable to accept that.  I tried with comparatively smaller value as follows: 

m=20; n = 1024; t=50 

It falls into infinite loop and eventually I had to terminate the program. 

![image](https://user-images.githubusercontent.com/20768904/174010627-39dd055d-0048-4edb-9c12-5fd2402f0541.png)

**Comment by ammuiyer** [comment]
Was this ever figured out?
